Remove caching
  - Fixes:
```
java.lang.RuntimeException: Build[bld-07ca0b6322a342f3a2569fb4d69aef69] does not have a configuration matching name[root]

```